pool:
  vmImage: 'ubuntu-14.04'

steps:
  - script: docker build -t $(dockerId)/$(imageName) .

  - script: |
      docker build -t $(dockerId).azurecr.io/$(imageName) .
      docker login -u $(dockerHubId) -p $(dockerHubPassword) $(dockerId).azurecr.io
      docker push $(dockerId).azurecr.io/$(imageName)
    displayName: 'Build and push Docker image'