version: '3'

services:

  redis:
    image: "redis:alpine"
    hostname: redis

  web:
    build: .
    image: flightapp.azurecr.io/webapp
    environment:
      - C_FORCE_ROOT=true
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    image: flightapp.azurecr.io/celeryworker
    command: celery -A bookingapi worker -l info
    volumes:
      - ./:/code
    depends_on:
      - redis

  celery-beat:
    build: .
    image: flightapp.azurecr.io/celerybeat
    command: celery -A bookingapi beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis