version: '3'

services:
  web:
    build: .
    image: flightapp.azurecr.io/webapp
    environment:
      - C_FORCE_ROOT=true
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis