# Generated by Django 2.1.4 on 2018-12-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('departure_from', models.CharField(max_length=30)),
                ('date_time_of_flight', models.DateTimeField()),
            ],
            options={
                'ordering': ['date_time_of_flight'],
            },
        ),
    ]
