# Generated by Django 2.1.4 on 2018-12-23 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_flightbooking_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbooking',
            name='id',
        ),
        migrations.AlterField(
            model_name='flightbooking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_booking', serialize=False, to='bookingapp.Flight'),
        ),
    ]
