# Generated by Django 2.1.4 on 2018-12-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_auto_20181223_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='flight',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_booking', serialize=False, to='bookingapp.Flight'),
        ),
    ]
