# Generated by Django 2.1.4 on 2018-12-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0006_passportphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
